# Generated by Django 5.0.2 on 2024-02-08 14:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('createdt', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updatedt', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
            options={
                'verbose_name': 'CommonsAmount',
                'verbose_name_plural': 'CommonsAmounts',
            },
        ),
        migrations.CreateModel(
            name='LotteryC60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('quran', 'Quran memorization lottery'), ('ziarat', 'Visiting religious places')], max_length=200, verbose_name='Lottery')),
                ('name', models.CharField(max_length=30, verbose_name='Lottery Name')),
            ],
            options={
                'verbose_name': 'LotteryC60',
                'verbose_name_plural': 'LotteryC60s',
            },
        ),
        migrations.CreateModel(
            name='NewsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='News Text')),
                ('createdt', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updatedt', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'News Text',
                'verbose_name_plural': 'News Texts',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediatype', models.CharField(choices=[('post', 'Post'), ('story', 'Story')], default=0, max_length=5, verbose_name='Media Type')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('updatedt', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('adv', models.BooleanField(default=False, verbose_name='Advertising')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='TableGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthnumber', models.FloatField(verbose_name='Month Number')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('monthamount', models.FloatField(blank=True, null=True, verbose_name='Month Amount')),
                ('subtraction', models.FloatField(verbose_name='subtraction')),
                ('friendships', models.FloatField(verbose_name='Friendships and affections')),
                ('numberannual', models.FloatField(verbose_name='Annual number')),
                ('amountannual', models.FloatField(verbose_name='Annual Amount')),
                ('totalsubtraction', models.FloatField(verbose_name='Total Subtraction')),
                ('totalfriendships', models.FloatField(verbose_name='Total Friendships')),
                ('gifts', models.CharField(max_length=200, verbose_name='Title Gifts')),
                ('monthsequence', models.FloatField(verbose_name='Month Sequence')),
                ('paytype', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Pay Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'TableGift',
                'verbose_name_plural': 'TableGifts',
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Table Type')),
                ('footer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'TableType',
                'verbose_name_plural': 'TableTypes',
            },
        ),
        migrations.CreateModel(
            name='CommonDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Deceased name')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery')),
                ('city', models.CharField(max_length=120, verbose_name='State/City')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('phoneagent', models.CharField(max_length=50, verbose_name='Phone Number Agent')),
                ('paystatus', models.BooleanField(default=False, verbose_name='Pay Status')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cd', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'CommonDead',
                'verbose_name_plural': 'CommonDeads',
            },
        ),
        migrations.CreateModel(
            name='Common70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Quadruple common name')),
                ('age', models.DateField(verbose_name='Age')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('sickness', models.CharField(blank=True, max_length=120, null=True, verbose_name='sickness')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery')),
                ('city', models.CharField(max_length=120, verbose_name='State/City')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('phoneagent', models.CharField(max_length=50, verbose_name='Phone Number Agent')),
                ('paystatus', models.BooleanField(default=False, verbose_name='Pay Status')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c70', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Common70',
                'verbose_name_plural': 'Common70s',
            },
        ),
        migrations.CreateModel(
            name='Common61',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Quadruple common name')),
                ('age', models.DateField(verbose_name='Age')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('sickness', models.CharField(blank=True, max_length=120, null=True, verbose_name='sickness')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery')),
                ('city', models.CharField(max_length=120, verbose_name='State/City')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('phoneagent', models.CharField(max_length=50, verbose_name='Phone Number Agent')),
                ('paystatus', models.BooleanField(default=False, verbose_name='PayStatus')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c61', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Common61',
                'verbose_name_plural': 'Common61s',
            },
        ),
        migrations.CreateModel(
            name='DoingDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Deceased name')),
                ('yearprayer', models.IntegerField(verbose_name='Years Passed prayer')),
                ('yearfasting', models.IntegerField(verbose_name='Years Passed fasting')),
                ('pilgrimage', models.CharField(max_length=200, verbose_name='Pilgrimage')),
                ('agent', models.CharField(max_length=200, verbose_name='Agent')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery')),
                ('city', models.CharField(max_length=120, verbose_name='State/City')),
                ('deposit', models.FloatField(verbose_name='Deposit')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('paystatus', models.BooleanField(default=False, verbose_name='Pay Status')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dd', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'DoingDead',
                'verbose_name_plural': 'DoingDeads',
            },
        ),
        migrations.CreateModel(
            name='JudiciaryDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Deceased name')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery')),
                ('city', models.CharField(max_length=120, verbose_name='State/City')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('phoneagent', models.CharField(max_length=50, verbose_name='Phone Number Agent')),
                ('paystatus', models.BooleanField(default=False, verbose_name='Pay Status')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jd', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'JudiciaryDead',
                'verbose_name_plural': 'JudiciaryDeads',
            },
        ),
        migrations.CreateModel(
            name='Common60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Quadruple common name')),
                ('age', models.DateField(verbose_name='Age')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('sickness', models.CharField(blank=True, max_length=120, null=True, verbose_name='sickness')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery')),
                ('city', models.CharField(max_length=120, verbose_name='State/City')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('phoneagent', models.CharField(max_length=50, verbose_name='Phone Number Agent')),
                ('paystatus', models.BooleanField(default=False, verbose_name='PayStatus')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c60', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount')),
                ('lottery', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lottery_c60', to='crm.lotteryc60', verbose_name='lottery')),
            ],
            options={
                'verbose_name': 'Common60',
                'verbose_name_plural': 'Common60s',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('seedate', models.DateTimeField(auto_now=True, verbose_name='See Date')),
                ('subject', models.CharField(max_length=120, verbose_name='Subject')),
                ('text', models.TextField(verbose_name='Text')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('force', models.BooleanField(default=False, verbose_name='Force Notification')),
                ('see', models.JSONField(blank=True, default={}, null=True, verbose_name='See')),
                ('user', models.ManyToManyField(related_name='user_msg', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='PublicAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Deceased name')),
                ('help_name', models.CharField(max_length=120, verbose_name='help name')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('useramount', models.FloatField(verbose_name='User Amount')),
                ('paystatus', models.BooleanField(default=False, verbose_name='Pay Status')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pa', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'PublicAssistance',
                'verbose_name_plural': 'PublicAssistances',
            },
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('createdt', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updatedt', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentuser', to=settings.AUTH_USER_MODEL)),
                ('socialmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentpost', to='crm.socialmedia')),
            ],
            options={
                'verbose_name': 'Comment Post',
                'verbose_name_plural': 'Comment Posts',
            },
        ),
        migrations.CreateModel(
            name='TableGiftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('countchances', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of Chances')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('countpay', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count Pay')),
                ('paystatus', models.BooleanField(default=False, verbose_name='Pay Status')),
                ('tablegift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabgiftusr', to='crm.tablegift', verbose_name='Gift Tables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TableGiftUser',
                'verbose_name_plural': 'TableGiftUsers',
            },
        ),
        migrations.CreateModel(
            name='TablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('payment', models.FloatField(verbose_name='Payment')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('tabgiftusr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='crm.tablegiftuser', verbose_name='Table Gift User')),
            ],
            options={
                'verbose_name': 'TablePayment',
                'verbose_name_plural': 'TablePayments',
            },
        ),
        migrations.AddField(
            model_name='tablegift',
            name='tabletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabgift', to='crm.tabletype', verbose_name='Table Type'),
        ),
        migrations.CreateModel(
            name='WinnerLottery60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('windate', models.DateTimeField(auto_now=True, verbose_name='Add Time')),
                ('common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winquran', to='crm.common60')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winlottery', to='crm.lotteryc60')),
            ],
            options={
                'verbose_name': 'WinnerLottery60',
                'verbose_name_plural': 'WinnerLottery60s',
            },
        ),
        migrations.CreateModel(
            name='WinTableLottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Lottery Title')),
                ('windate', models.DateTimeField(auto_now_add=True, verbose_name='Win Date')),
                ('tabgiftusr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabwingift', to='crm.tablegiftuser', verbose_name='Table Gift User')),
            ],
            options={
                'verbose_name': 'WinTableLottery',
                'verbose_name_plural': 'WinTableLotterys',
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeuser', to=settings.AUTH_USER_MODEL)),
                ('socialmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='crm.socialmedia')),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'unique_together': {('user', 'socialmedia')},
            },
        ),
        migrations.CreateModel(
            name='ViewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('socialmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewpost', to='crm.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post View',
                'verbose_name_plural': 'Post Views',
                'unique_together': {('user', 'socialmedia')},
            },
        ),
    ]
