# Generated by Django 4.2 on 2023-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcmtoken',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='FCM Token'),
        ),
    ]
