# Generated by Django 4.2 on 2023-08-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcmtoken',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='FCM Token'),
        ),
    ]
