# Generated by Django 4.2 on 2023-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_common60_amount_common60_status_common61_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='common60',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Link'),
        ),
        migrations.AddField(
            model_name='common61',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Link'),
        ),
        migrations.AddField(
            model_name='common70',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Link'),
        ),
        migrations.AddField(
            model_name='commondead',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Link'),
        ),
        migrations.AddField(
            model_name='doingdead',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Link'),
        ),
        migrations.AddField(
            model_name='judiciarydead',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Link'),
        ),
        migrations.AddField(
            model_name='publicassistance',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Link'),
        ),
    ]
