# Generated by Django 4.2.1 on 2023-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='common60',
            name='age',
            field=models.DateField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='common60',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='common60',
            name='phoneagent',
            field=models.CharField(max_length=50, verbose_name='Phone Number Agent'),
        ),
        migrations.AlterField(
            model_name='common61',
            name='age',
            field=models.DateField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='common61',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='common61',
            name='phoneagent',
            field=models.CharField(max_length=50, verbose_name='Phone Number Agent'),
        ),
        migrations.AlterField(
            model_name='common70',
            name='age',
            field=models.DateField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='common70',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='common70',
            name='phoneagent',
            field=models.CharField(max_length=50, verbose_name='Phone Number Agent'),
        ),
        migrations.AlterField(
            model_name='commondead',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='commondead',
            name='phoneagent',
            field=models.CharField(max_length=50, verbose_name='Phone Number Agent'),
        ),
        migrations.AlterField(
            model_name='doingdead',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='judiciarydead',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='judiciarydead',
            name='phoneagent',
            field=models.CharField(max_length=50, verbose_name='Phone Number Agent'),
        ),
    ]
