# Generated by Django 4.2.1 on 2023-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_delete_book_alter_common60_age_alter_common60_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicassistance',
            name='name',
            field=models.CharField(default='rrr', max_length=150, verbose_name='Deceased name'),
            preserve_default=False,
        ),
    ]
