# Generated by Django 4.2 on 2023-07-23 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_publicassistance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicassistance',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
