# Generated by Django 4.2 on 2023-07-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lottery_common60_lottery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common60',
            name='lottery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lottery_c60', to='crm.lottery', verbose_name='lottery'),
        ),
    ]
