# Generated by Django 4.2 on 2023-08-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_notification_user_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerLotZiarat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('addtime', models.DateField(auto_now=True, verbose_name='Add Time')),
                ('common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winziarat', to='crm.common60')),
            ],
            options={
                'verbose_name': 'WinnerLotZiarat',
                'verbose_name_plural': 'WinnerLotZiarats',
            },
        ),
        migrations.CreateModel(
            name='WinnerLotQuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('addtime', models.DateField(auto_now=True, verbose_name='Add Time')),
                ('common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winquran', to='crm.common60')),
            ],
            options={
                'verbose_name': 'LotteryQuran',
                'verbose_name_plural': 'LotteryQurans',
            },
        ),
    ]
