# Generated by Django 4.2 on 2023-08-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_winnerlotziarat_winnerlotquran'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerLottery60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('addtime', models.DateField(auto_now=True, verbose_name='Add Time')),
                ('common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winquran', to='crm.common60')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winlottery', to='crm.lottery')),
            ],
            options={
                'verbose_name': 'WinnerLottery60',
                'verbose_name_plural': 'WinnerLottery60s',
            },
        ),
        migrations.RemoveField(
            model_name='winnerlotziarat',
            name='common',
        ),
        migrations.DeleteModel(
            name='WinnerLotQuran',
        ),
        migrations.DeleteModel(
            name='WinnerLotZiarat',
        ),
    ]
