# Generated by Django 4.2 on 2023-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_winnerlottery60_remove_winnerlotziarat_common_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winnerlottery60',
            old_name='addtime',
            new_name='wintime',
        ),
        migrations.RemoveField(
            model_name='winnerlottery60',
            name='status',
        ),
    ]
