# Generated by Django 4.2 on 2023-08-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_rename_addtime_winnerlottery60_wintime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winnerlottery60',
            old_name='wintime',
            new_name='windate',
        ),
    ]
