# Generated by Django 4.2 on 2023-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_rename_wintime_winnerlottery60_windate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerlottery60',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
    ]
