# Generated by Django 4.2.1 on 2023-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_winnerlottery60_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='see',
            field=models.JSONField(default=False, verbose_name='See'),
        ),
    ]
