# Generated by Django 4.2 on 2023-08-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_notification_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='see',
            field=models.JSONField(blank=True, null=True, verbose_name='See'),
        ),
    ]
