# Generated by Django 4.2 on 2023-08-10 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0028_remove_tablegift3_gifttable24_remove_tablegift3_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableGift1',
            new_name='TableGift',
        ),
        migrations.AlterModelOptions(
            name='tablegift',
            options={'verbose_name': 'TableGift', 'verbose_name_plural': 'TableGifts'},
        ),
    ]
