# Generated by Django 4.2 on 2023-08-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_rename_tablegift1_tablegift_alter_tablegift_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiftTable24',
            new_name='TableGift24',
        ),
        migrations.AlterModelOptions(
            name='tablegift24',
            options={'verbose_name': 'TableGift24', 'verbose_name_plural': 'TableGift24s'},
        ),
        migrations.RenameField(
            model_name='tablegift',
            old_name='gifttable24',
            new_name='tablegift24',
        ),
    ]
