# Generated by Django 4.2 on 2023-08-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_rename_gifttable24_tablegift24_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountgiftpay',
            name='gifttable',
        ),
        migrations.AddField(
            model_name='amountgiftpay',
            name='tablegift',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='giftpay', to='crm.tablegift24', verbose_name='Table Gift'),
            preserve_default=False,
        ),
    ]
