# Generated by Django 4.2 on 2023-08-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_tablegiftuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('tablegiftuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amountgift', to='crm.tablegiftuser', verbose_name='Table Gift')),
            ],
            options={
                'verbose_name': 'TableAmount',
                'verbose_name_plural': 'TableAmounts',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tableamount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qst', to='crm.tableamount', verbose_name='TableAmount')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
            },
        ),
    ]
