# Generated by Django 4.2 on 2023-08-14 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_tableinstallment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegift',
            name='paytype',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Pay Type'),
        ),
    ]
