# Generated by Django 4.1.3 on 2023-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_alter_tablegiftuser_tablegift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableamount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
