# Generated by Django 4.1.3 on 2023-08-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_tablepayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableName',
            new_name='TableType',
        ),
        migrations.AlterModelOptions(
            name='tabletype',
            options={'verbose_name': 'TableType', 'verbose_name_plural': 'TableTypes'},
        ),
    ]
