# Generated by Django 4.1.3 on 2023-08-17 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_rename_tablename_tabletype_alter_tabletype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegiftuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablegift',
            name='tablename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabgift', to='crm.tabletype', verbose_name='Table Type'),
        ),
        migrations.AlterField(
            model_name='tabletype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Table Type'),
        ),
    ]
