# Generated by Django 4.1.3 on 2023-08-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_tablegiftuser_created_alter_tablegift_tablename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablegift',
            old_name='tablename',
            new_name='tabletype',
        ),
    ]
