# Generated by Django 4.2 on 2023-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_rename_tablename_tablegift_tabletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegiftuser',
            name='numchances',
            field=models.IntegerField(default=1, verbose_name='Number of Chances'),
        ),
        migrations.AddField(
            model_name='tablegiftuser',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='Pay Status'),
        ),
    ]
