# Generated by Django 4.2 on 2023-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_tablegiftuser_numchances_tablegiftuser_paystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablegiftuser',
            name='numchances',
        ),
        migrations.AddField(
            model_name='tablegiftuser',
            name='countchances',
            field=models.IntegerField(default=1, verbose_name='Count of Chances'),
        ),
    ]
