# Generated by Django 4.2 on 2023-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_remove_tablegiftuser_numchances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepayment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
