# Generated by Django 4.2 on 2023-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_tablepayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegiftuser',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
