# Generated by Django 4.2 on 2023-08-21 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0064_alter_tablepayment_tabgiftusr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepayment',
            name='tabgiftusr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='crm.tablegiftuser', verbose_name='Table Gift User'),
        ),
        migrations.CreateModel(
            name='WinTableLottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windate', models.DateTimeField(auto_now_add=True, verbose_name='Win Date')),
                ('tabgiftusr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabwingift', to='crm.tablegiftuser', verbose_name='Table Gift User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbwinusr', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'WinTableLottery',
                'verbose_name_plural': 'WinTableLotterys',
            },
        ),
        migrations.CreateModel(
            name='CreateLotteryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Lottery Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('wintablot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crtlottab', to='crm.wintablelottery')),
            ],
            options={
                'verbose_name': 'CreateLotteryTable',
                'verbose_name_plural': 'CreateLotteryTables',
            },
        ),
    ]
