# Generated by Django 4.2 on 2023-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_alter_tablepayment_tabgiftusr_wintablelottery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wintablelottery',
            name='user',
        ),
        migrations.AddField(
            model_name='wintablelottery',
            name='title',
            field=models.CharField(default=1, max_length=150, verbose_name='Lottery Title'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CreateLotteryTable',
        ),
    ]
