# Generated by Django 4.2 on 2023-08-21 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_remove_wintablelottery_user_wintablelottery_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegiftuser',
            name='countchances',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count of Chances'),
        ),
        migrations.AlterField(
            model_name='tablegiftuser',
            name='countpay',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Count Pay'),
        ),
    ]
