# Generated by Django 4.2 on 2023-08-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_lotteryc60_winnerlottery60_common60_lottery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common60',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='common60',
            name='link',
        ),
        migrations.RemoveField(
            model_name='common61',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='common61',
            name='link',
        ),
        migrations.RemoveField(
            model_name='common70',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='common70',
            name='link',
        ),
        migrations.RemoveField(
            model_name='commondead',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='commondead',
            name='link',
        ),
        migrations.RemoveField(
            model_name='doingdead',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='doingdead',
            name='link',
        ),
        migrations.RemoveField(
            model_name='judiciarydead',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='judiciarydead',
            name='link',
        ),
        migrations.RemoveField(
            model_name='publicassistance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='publicassistance',
            name='link',
        ),
        migrations.AddField(
            model_name='common60',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='PayStatus'),
        ),
        migrations.AddField(
            model_name='common61',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='PayStatus'),
        ),
        migrations.AddField(
            model_name='common70',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='PayStatus'),
        ),
        migrations.AddField(
            model_name='commondead',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='PayStatus'),
        ),
        migrations.AddField(
            model_name='doingdead',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='PayStatus'),
        ),
        migrations.AddField(
            model_name='judiciarydead',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='PayStatus'),
        ),
        migrations.AddField(
            model_name='publicassistance',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='PayStatus'),
        ),
    ]
