# Generated by Django 4.2 on 2023-08-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_remove_common60_amount_remove_common60_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('amount', models.IntegerField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'CommonsAmount',
                'verbose_name_plural': 'CommonsAmounts',
            },
        ),
    ]
