# Generated by Django 4.2 on 2023-08-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_commonsamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='common60',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common61',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common70',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commondead',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doingdead',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judiciarydead',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicassistance',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.commonsamount', verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
