# Generated by Django 4.1.3 on 2023-08-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_common60_amount_common61_amount_common70_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonsamount',
            name='title',
            field=models.CharField(default='test', max_length=150, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
