# Generated by Django 4.1.3 on 2024-01-07 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0075_publicassistance_useramount_alter_common70_paystatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Post Media',
                'verbose_name_plural': 'Post Media',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Storys',
            },
        ),
        migrations.CreateModel(
            name='ViewStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewsory', to='crm.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewuserstory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story View',
                'verbose_name_plural': 'Story Views',
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.CreateModel(
            name='ViewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('postmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewpost', to='crm.postmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewuserpost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post View',
                'verbose_name_plural': 'Post Views',
                'unique_together': {('user', 'postmedia')},
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('postmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='crm.postmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'unique_together': {('user', 'postmedia')},
            },
        ),
    ]
