# Generated by Django 4.1.3 on 2024-01-10 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0081_alter_socialmedia_mediatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='News Text')),
                ('createdt', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updatedt', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
            options={
                'verbose_name': 'News Text',
                'verbose_name_plural': 'News Texts',
            },
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('socialmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentpost', to='crm.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Post',
                'verbose_name_plural': 'Comment Posts',
            },
        ),
    ]
