# Generated by Django 4.1.3 on 2024-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_newstext_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='updatedt',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
