# Generated by Django 4.1.3 on 2024-01-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_socialmedia_updatedt'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstext',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
